# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gentoo-Probe
version:      1.0.4
version_from: lib/Gentoo/Probe.pm
installdirs:  site
requires:
    Getopt::WonderBra:             1.04
    Inline::Python:                0.22
    String::Escape:                0
    Term::ReadLine:                1.02
    Text::Number:                  0.8

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
